# Lab 6
### Due by 11:59pm, Sunday, November 17th.
#### Submission: Please replace firstname, lastname and permid in the file name with yours before submitting on Canvas.
Reminder: For Multiple Choice Questions, your answers should be formatted as follows:
```python
def ans_q1():
  return 'C' # if the C is the selected option
  # Please only add the option and nothing more.
```
## Grading
Multiple Choice, T/F, Fill-in-the-blank Questions: 10% each. Programming Questions: 25% each.

**Lab TA:**

### Multiple Choice, T/F, Fill-in-the-blank Questions:

**Q1:** Which of the following commands will generate an array of 10 numbers evenly spaced between 1 and 30?

A. `np.random.randint(1,30,10)`

B. `np.linspace(1,30,10)`

C. `np.arange(1,30,1)`

D. `np.random.rand(1,30)`

In [ ]:
def ans_q1():
  return 'B'

**Q2.** Which of the following commands will **not** produce a 3x3 identity matrix in NumPy?

A. np.ones((3, 3))

B. np.identity(3)

C. np.eye(3)

D. np.diag([1,1,1])


In [ ]:
def ans_q2():
  return 'D'

**Q3.** Given two **matrices** A and B, which of the following commands will produce a different output than others?

A. A@B

B. np.multiply(A,B)

C. np.dot(A,B)

D. np.matmul(A,B)

In [ ]:
def ans_q3()
  return 'B'

**Q4.**
Given the following code snippet, what will be the output?

   ```python
   import numpy as np
   a = np.array([1, 2, 3])
   b = np.array([4, 5, 6])
   result = np.dot(a, b)
   print(result)
   ```

   A. `[4, 10, 18]`  

   B. `32`  

   C. `[5, 7, 9]`  

   D. `[1, 2, 3, 4, 5, 6]`  

In [ ]:
def ans_q4():
  return 'B'

**Q5:** Given a matrix `B`, which of the following methods in `numpy` will correctly compute its rank?

A) `np.linalg.rank(B)`

B) `np.linalg.matrix_rank(B)`

C) `np.rank(B)`

D) `np.trace(B)`


In [ ]:
def ans_q5():
  return 'B'

# Programming Questions:

INSTRUCTIONS: Write function, class or method definition(s) as described. If a template is provided, insert code or make changes only where specified. **Do not modify the names of the functions, methods or classes provided in the question or the template.**

**Q6.** Write a Python function that solves a system of linear equations given in matrix form \( Ax = b \) using NumPy.

   - The function should accept two inputs: a 2D array `A` (coefficient matrix) and a 1D array `b` (right-hand side values).
   - Use NumPy's `linalg.solve` function to find the solution vector `x`.
   - If the system is not solvable (singular matrix, or overdetermined or underdetermined system), the function should return `"System cannot be solved"`.

   **Usage Example:**
   ```python
   A1 = np.array([[3, 1], [1, 2]])
   A2 = np.array([[3, 1], [1, 2], [3, 4]])
   A3 = np.array([[1, 1], [2, 2]])
   b = np.array([9, 8])
   solution1 = solve_linear_system(A1, b)
   print("Solution 1:",solution1)
   solution2 = solve_linear_system(A2, b)
   print("Solution 2:",solution2)
   solution3 = solve_linear_system(A3, b)
   print("Solution 3:",solution3)
   ```
   produces:
   ```python
   Solution 1: [2. 3.]
   Solution 2: System cannot be solved: the matrix A is not square (overdetermined or underdetermined).
   Solution 3: System cannot be solved: the matrix A is singular (determinant is zero).
   ```


In [2]:
import numpy as np
def solve_linear_system(A, b):
    # Check if A is a square matrix
    # YOUR CODE
    shape = A.shape
    if shape[0] != shape[1]:
        return "System cannot be solved: the matrix A is not square (overdetermined or underdetermined)."

    # Check if A is singular (i.e., does not have an inverse)
    # YOUR CODE
    if np.linalg.det(A) == 0:
        return "System cannot be solved: the matrix A is singular (determinant is zero)."

    try:
        # Attempt to solve the system
        # YOUR CODE
        x = np.linalg.solve(A, b)
        return x
    except np.linalg.LinAlgError as e:
        # Catch any linear algebra error and return a message
        return f"System cannot be solved: {str(e)}"

# Example usage:
A1 = np.array([[3, 1], [1, 2]])
A2 = np.array([[3, 1], [1, 2], [3, 4]])
A3 = np.array([[1, 1], [2, 2]])
b = np.array([9, 8])
solution1 = solve_linear_system(A1, b)
print("Solution 1:",solution1)
solution2 = solve_linear_system(A2, b)
print("Solution 2:",solution2)
solution3 = solve_linear_system(A3, b)
print("Solution 3:",solution3)

Solution 1: [2. 3.]
Solution 2: System cannot be solved: the matrix A is not square (overdetermined or underdetermined).
Solution 3: System cannot be solved: the matrix A is singular (determinant is zero).


**Q7.**
Given two matrices A and B, compute the following by completing the code template below:

a. The element-wise product of A and B

b. The dot product of A and B

c. The determinant of each matrix

d. The inverse (if defined) of each matrix

e. The eigenvalues and eigenvectors of each matrix, if defined.

f. min, max, mean, sum of each matrix.

In [6]:
import numpy as np

def matrix_operations(A, B):
    results = {}

    # Ensure matrices A and B have the same dimensions for element-wise operations
    if A.shape[0] == B.shape[0]: # YOUR CODE: CHECK FOR DIMENSION MATCHING
        # a. Element-wise product
        results['elementwise_product'] = A * B
    else:
        results['elementwise_product'] = "Not defined: Matrices have different shapes."

    # b. Dot product (only defined if columns in A == rows in B)
    try:
        results['dot_product'] = np.dot(A, B)
    except ValueError:
        results['dot_product'] = "Not defined: Dimensions do not align for dot product."

    # c. Determinant of each matrix (only for square matrices)
    if A.shape[0] == A.shape[1]:
        results['determinant_A'] = np.linalg.det(A)
    else:
        results['determinant_A'] = "Not defined: A is not square."

    if B.shape[0] == B.shape[1]:
        results['determinant_B'] = np.linalg.det(B)
    else:
        results['determinant_B'] = "Not defined: B is not square."

    # d. Inverse of each matrix (only for square matrices with non-zero determinant)
    if A.shape[0] == A.shape[1] and np.linalg.det(A) != 0:
        results['inverse_A'] = np.linalg.inv(A)
    else:
        results['inverse_A'] = "Not defined: A is not square or is singular."

    if B.shape[0] == B.shape[1] and np.linalg.det(B) != 0:
        results['inverse_B'] = np.linalg.inv(B)
    else:
        results['inverse_B'] = "Not defined: B is not square or is singular."

    # e. Eigenvalues and eigenvectors (only for square matrices)
    if A.shape[0] == A.shape[1]:
        eigvals_A, eigvecs_A = np.linalg.eig(A)
        results['eigenvalues_A'] = eigvals_A
        results['eigenvectors_A'] = eigvecs_A
    else:
        results['eigenvalues_A'] = "Not defined: A is not square."
        results['eigenvectors_A'] = "Not defined: A is not square."

    if B.shape[0] == B.shape[1]:
        eigvals_B, eigvecs_B = np.linalg.eig(B)
        results['eigenvalues_B'] = eigvals_B
        results['eigenvectors_B'] = eigvecs_B
    else:
        results['eigenvalues_B'] = "Not defined: B is not square."
        results['eigenvectors_B'] = "Not defined: B is not square."

    # f. Min, max, mean, sum of each matrix
    results['min_A'] = np.min(A)
    results['max_A'] = np.max(A)
    results['mean_A'] = np.mean(A)
    results['sum_A'] = np.sum(A)

    results['min_B'] = np.min(B)
    results['max_B'] = np.max(B)
    results['mean_B'] = np.mean(B)
    results['sum_B'] = np.sum(B)

    return results

# Example usage
A = np.array([[2, 4], [1, 3]])
B = np.array([[5, 7], [6, 8]])
results = matrix_operations(A, B)

# Display the results
for key, value in results.items():
    print(f"{key}:")
    print(value)
    print()


elementwise_product:
[[10 28]
 [ 6 24]]

dot_product:
[[34 46]
 [23 31]]

determinant_A:
2.0

determinant_B:
-2.000000000000003

inverse_A:
[[ 1.5 -2. ]
 [-0.5  1. ]]

inverse_B:
[[-4.   3.5]
 [ 3.  -2.5]]

eigenvalues_A:
[0.43844719 4.56155281]

eigenvectors_A:
[[-0.93153209 -0.84212294]
 [ 0.36365914 -0.5392856 ]]

eigenvalues_B:
[-0.15206735 13.15206735]

eigenvectors_B:
[[-0.80537591 -0.65146248]
 [ 0.59276441 -0.75868086]]

min_A:
1

max_A:
4

mean_A:
2.5

sum_A:
10

min_B:
5

max_B:
8

mean_B:
6.5

sum_B:
26



In [ ]:
# Expected results:
elementwise_product:
[[10 28]
 [ 6 24]]

dot_product:
[[34 46]
 [23 31]]

determinant_A:
2.0

determinant_B:
-1.999999999999998

inverse_A:
[[ 1.5 -2. ]
 [-0.5  1. ]]

inverse_B:
[[-4.   3.5]
 [ 3.  -2.5]]

eigenvalues_A:
[0.43844719 4.56155281]

eigenvectors_A:
[[-0.93153209 -0.84212294]
 [ 0.36365914 -0.5392856 ]]

eigenvalues_B:
[-0.15206735 13.15206735]

eigenvectors_B:
[[-0.80537591 -0.65146248]
 [ 0.59276441 -0.75868086]]

min_A:
1

max_A:
4

mean_A:
2.5

sum_A:
10

min_B:
5

max_B:
8

mean_B:
6.5

sum_B:
26