# Numpy!

In [1]:
import numpy as np

## Overview

Numpy allows us to do many useful operations with numbers in python (hence the name) including linear algebra, fourier transforms, and other useful scientific computing functions.

## Installing

Numpy is not a built in package to python. You can install it using the built in python package manager (pip) with the following command:
```bash
pip install numpy
```
Once it is installed, you can import it using the statement shown here:

In [ ]:
import numpy as np

Note: the `as np` bit on the end is not required, but simply aliases the numpy module as `np` so that way we can just refer to it by the shorthand `np`

## Basic Usage

Lets use numpy to solve the following system of linear equations:
$$2x_{1}+1x_{2}=3$$
$$1x_{1}+2x_{2}=5$$
We can do this using numpy's `linalg` submodule by representing this system as the following matrix equation:
$$A\vec{x}=\vec{b}$$
where:
$$A=\begin{bmatrix}
2 & 1 \\
1 & 2 \\
\end{bmatrix}$$
$$\vec{b}=\begin{bmatrix}
3 \\
5 \\
\end{bmatrix}$$
and
$$\vec{x}=\begin{bmatrix}
x_{1} \\
x_{2} \\
\end{bmatrix}$$
where we want to solve for the vector x.

In [19]:
import numpy as np

# you can ignore this, it is just to make sure that resulting vectors & lists are printed with 2 decimal places
np.set_printoptions(formatter={'float': lambda x: f"{x:.2f}"})

# define our variables
# matricies are represented by `lists of lists`
# matricies are entered in row-major order meaning that the inner arrays are the rows
A = [[2, 1], [1, 2]]
# vectors are just represented by a list
b = [3, 5]

# solve the equation
# np.linalg.solve solves the matrix equation Ax = b for x given A and b
x = np.linalg.solve(A, b)

# print out the vector solution
print(f"x = {x}")

# extract x1 and x2
for i in range(len(x)):
    print(f"x{i+1} = {x[i]:.2f}")

# check our solution
for i in range(len(A)):
    lhs = 0
    for j in range(len(A[i])):
        lhs += A[i][j] * x[j]
    rhs = b[i]
    # need to use np.isclose here because of floating point error
    if np.isclose(lhs, rhs):
        print(f"Equation {i + 1} holds.")
    else:
        print(f"Equation {i + 1} does not hold.")

x = [0.33 2.33]
x1 = 0.33
x2 = 2.33
Equation 1 holds.
Equation 2 holds.


this is much more useful when solving more complex systems.

In [29]:
import numpy as np
import random as rand

# you can ignore this, it is just to make sure that resulting vectors & lists are printed with 2 decimal places
np.set_printoptions(formatter={'float': lambda x: f"{x:.2f}"})

# Same Example as above, but solving a randomly generated system with n equations and n unknowns (nxn matrix)

# size of our matrix
n = 15

# define our variables
# matricies are represented by `lists of lists`
# matricies are entered in row-major order meaning that the inner arrays are the rows
A = np.array([[rand.randint(0, 10) for _ in range(n)] for _ in range(n)])
# vectors are just represented by a list
b = [rand.randint(0, 10) for _ in range(n)]

# show A and b
print(f"A = \n{A}")
print(f"b = {b}")

# solve the equation
# np.linalg.solve solves the matrix equation Ax = b for x given A and b
x = np.linalg.solve(A, b)

# print out the vector solution
print(f"x = {x}")

# extract x1 and x2
for i in range(len(x)):
    print(f"x{i+1} = {x[i]:.2f}")

# check our solution
for i in range(len(A)):
    lhs = 0
    for j in range(len(A[i])):
        lhs += A[i][j] * x[j]
    rhs = b[i]
    # need to use np.isclose here because of floating point error
    if np.isclose(lhs, rhs):
        print(f"Equation {i + 1} holds.")
    else:
        print(f"Equation {i + 1} does not hold.")

A = 
[[ 8  5  5  4  3  6  8  1  2  6  9  3  9 10  6]
 [ 8 10  9  8 10  2  5  8 10  4  7  5  5  8  1]
 [ 0  9  4  3  3  1  9  7  2  8  9  7  4  8  7]
 [ 6  0  5  0  6 10  1  3  7  1 10  5  8  3  0]
 [ 9  0  6 10  3  4  4  0  0 10  2  6  2  4  3]
 [ 5  1  8  1  7 10  2  4  5  8  1  4  4  3 10]
 [ 5  5  6  6  7  8  2  3  6  3  2  9  2  1  3]
 [ 1  7  4  0 10  7  5  7  7  3  2  1  1  7  8]
 [ 9  9  8 10  6  4  5 10  5  9  5  4  1  4  2]
 [ 2  6  6 10  9  1 10 10  3  0  5  6  4  7 10]
 [ 1  2  5  6  9  8  8  8  9  7  7  0  5  2  8]
 [ 2  4  3  6  5  4  7  9 10  1  6  7  3  9  2]
 [ 8  7  4  8 10  7  4 10  1  0  5 10  3  4  6]
 [ 6  8  1  9  5  7  4  5  4  3  3  2  7  1 10]
 [ 7 10  2  8  2  4 10 10  7  3  1  2  0  4  4]]
b = [8, 6, 2, 4, 9, 10, 9, 2, 5, 0, 8, 5, 2, 7, 1]
x = [-3.88 0.71 0.23 0.40 1.56 2.62 1.98 2.45 -3.05 2.54 -7.08 0.34 8.33 0.84
 -5.97]
x1 = -3.88
x2 = 0.71
x3 = 0.23
x4 = 0.40
x5 = 1.56
x6 = 2.62
x7 = 1.98
x8 = 2.45
x9 = -3.05
x10 = 2.54
x11 = -7.08
x12 = 0.34
x13 = 8.33


## Other useful numpy functions

`transpose` - Transposes a matrix or vector, flipping it about its diagonal. e.g.
$$\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}^{T}=
\begin{bmatrix}
1 & 4 & 7 \\
2 & 5 & 8 \\
3 & 6 & 9
\end{bmatrix}$$
`linalg.eig` and `linalg.eigenvalues` - Calculates the eigenvectors and eigenvalues of a given matrix.

`linalg.det` - Calculates the determinant (area scale factor) of a given matrix. e.g. for a 2x2 matrix
$$\det(\begin{bmatrix}
a & b \\
c & d \\
\end{bmatrix})=ad-bc$$
`lianlg.inv` - Computes the inverse of the supplied matrix. e.g. computes A^-1 from A such that:
$$A^{-1}A=I$$

Examples:

In [27]:
import numpy as np

# you can ignore this, it is just to make sure that resulting vectors & lists are printed with 2 decimal places
np.set_printoptions(formatter={'float': lambda x: f"{x:.2f}"})

# Transpose
A = [[1,2,3],[4,5,6],[7,8,9]]
At = np.transpose(A)
print(f"A^T = \n{At}")

# Eigenvalues
A = [[5,0],[0,2]]
eigenvalues = np.linalg.eigvals(A)
values_and_vectors = np.linalg.eig(A)
print(f"eigenvalues: {eigenvalues}")
print(f"eigenvalue-eigenvector pairs: {values_and_vectors}")

# Determinant
A = [[1, 2], [2, 4]]
det = np.linalg.det(A)
print(f"det(A) = {det}")

# Inverse
A = [[1, 2], [6, 8]]
Ainv = np.linalg.inv(A)
print(f"inverse of A: \n{Ainv}")

A^T = 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
eigenvalues: [5.00 2.00]
eigenvalue-eigenvector pairs: (array([5.00, 2.00]), array([[1.00, 0.00],
       [0.00, 1.00]]))
det(A) = 0.0
inverse of A: 
[[-2.00 0.50]
 [1.50 -0.25]]


## np.array

Numpy has its own array type, which is very similar to the builtin python list type, however it allows matricies and vectors to be handled in an object oriented style as opposed to a functional style. Most Numpy functions will work if supplied with either a python list or a numpy array object.

In [31]:
import numpy as np

# Regular python list
boring_list = [[1, 2], [3, 4]]

# We can make a numpy array using the np.array function
numpy_array = np.array([[1, 2], [3, 4]])

print(f"python list: {boring_list}")
print(f"numpy array: \n{numpy_array}")

python list: [[1, 2], [3, 4]]
numpy array: 
[[1 2]
 [3 4]]


## Use Case: Using numpy to calculate a least-squares best fit curve & plotting with matplotlib

here we will find the lest-squares best fit parabola for some given data using numpy, and then plot the result with matplotlib.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt